spring:
  jackson:
    serialization:
      write-dates-as-timestamps: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://123.60.133.64:5432/petpat
    username: postgres
    password: petpat2023

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

gorit:
  file:
    root:
      path: D://file/

sa-token:
  #   token-name: token
  #   # 30 days
  #   timeout: 2592000
  #   # no expiration
  #   activity-timeout: -1
  #   # multi login
  #   is-concurrent: true
  #   is-share: true
  token-style: uuid
  is-log: true
